extends RefCounted
# Spoken lines for Mara. Same voice on every clip.

const ROWS: Array = [
	["You're fine, there's not a lot of my kind in this area. I'm a Çampire—vampire and werecat somewhere down the line. The wings plus the tail are a fun conversation starter.", "campire"],
	["When you're ready, the drink menu is on the wall. Have a look — then I can take your order.", "menu"],
	["You're fine — take your time. The board is there when you're ready.", "opener"],
	["What's your order?", "order"],
	["A drink and a food.", "drink_and"],
	["A drink y a food.", "drink_y"],
	["Today I'd like you to say y instead of and — a drink y a food.", "teach_y"],
	["Extras use con, like con azúcar.", "teach_con"],
	["Today, un and una mean a, or one — un café, a coffee.", "teach_article"],
	["Un café y una galleta. Y still joins them, and extras still use con.", "teach_example"],
	["Un or una, then a drink y a food, con if you want extras.", "teach_later"],
	["Adiós, y buenas noches", "bye_y"],
	["Adiós, and buenas noches", "bye_and"],
	["Hear the tables first. I'll call when your order is ready.", "hear_tables"],
	["Give it a moment. I'll call you.", "give_moment"],
	["Your order's at the counter.", "at_counter"],
	["The dish cart is by the counter. Cups and plates go there to be washed.", "dish_wash"],
	["Your order's ready.", "order_ready"],
	["Not yet. Hear the tables first — I'll call you.", "not_yet"],
	["Here you go — that's ready.", "here_you_go"],
	["I'll call you when it's ready.", "ill_call"],
	["It's chilly tonight. That's why you light the fire at home.", "chilly"],
	["Dishes in the cart first. Then we say goodbye.", "dishes_first"],
	["The door's there when you're ready.", "door_ready"],
	["That's already yours. Sit if you like — the room is for lingering.", "lingering"],
	["Not quite enough for the board today — and you've already practiced what's up. Sit if you like.", "practiced_up"],
	["Take your time — look at the board again if you need to.", "take_time"],
	["I didn't catch that.", "didnt_catch"],
	["You'll want the learning card from the elder's basket first — no borrowing past zero.", "need_card"],
	["Almost — here we say y, and extras use con.", "almost_y_con"],
	["Almost — here we say y.", "almost_y"],
	["Almost — extras use con.", "almost_con"],
	["Almost — un or una means a, or one.", "almost_article"],
	["and something to eat with it? A food from the board too.", "eat_with"],
	["and a drink to go with it?", "drink_with"],
	["Your card's a little short — but we can practice what's on the board.", "practice_short"],
	["What do we call", "what_call"],
	["in Spanish?", "in_spanish"],
	["Not quite — look for", "look_for"],
	["The word is", "word_is"],
	["Come back when you're ready to try again.", "try_again"],
	["That sounds lovely, dear.", "lovely"],
	["The learning program added", "added_pesos"],
	["pesos to your card for practice.", "pesos_practice"],
	["You've practiced plenty for today — the word will stick.", "practiced_plenty"],
	["once more on your way out and it'll feel natural.", "feel_natural"],
	["That extra is", "that_extra"],
	["Spanish on this wall.", "spanish_wall"],
	["Finish first — then the cup and plate go in the cart.", "finish_first"],
	["pesos for this order.", "pesos_for"],
	["I can't start it until you have enough on the card.", "cant_start"],
	["y", "y"],
	["con", "con"],
	["un", "un"],
	["una", "una"],
	["café", "cafe"],
	["té", "te"],
	["muffin", "muffin"],
	["chocolate caliente", "chocolate"],
	["espresso", "espresso"],
	["croissant", "croissant"],
	["tostada", "tostada"],
	["galleta", "galleta"],
	["bolillo", "bolillo"],
	["leche", "leche"],
	["azúcar", "azucar"],
	["crema", "crema"],
	["calentado", "calentado"],
	["frío", "frio"],
	["coffee", "coffee"],
	["tea", "tea"],
	["toast", "toast"],
	["cookie", "cookie"],
	["milk", "milk"],
	["sugar", "sugar"],
	["creamer", "creamer"],
	["hot chocolate", "hot_chocolate"],
]

const CLIPS := {
	"campire": preload("res://audio/mara_campire.mp3"),
	"menu": preload("res://audio/mara_menu.mp3"),
	"opener": preload("res://audio/mara_opener.mp3"),
	"order": preload("res://audio/mara_order.mp3"),
	"drink_and": preload("res://audio/mara_drink_and.mp3"),
	"drink_y": preload("res://audio/mara_drink_y.mp3"),
	"teach_y": preload("res://audio/mara_teach_y.mp3"),
	"teach_con": preload("res://audio/mara_teach_con.mp3"),
	"teach_article": preload("res://audio/mara_teach_article.mp3"),
	"teach_example": preload("res://audio/mara_teach_example.mp3"),
	"teach_later": preload("res://audio/mara_teach_later.mp3"),
	"bye_y": preload("res://audio/mara_bye_y.mp3"),
	"bye_and": preload("res://audio/mara_bye_and.mp3"),
	"hear_tables": preload("res://audio/mara_hear_tables.mp3"),
	"give_moment": preload("res://audio/mara_give_moment.mp3"),
	"at_counter": preload("res://audio/mara_at_counter.mp3"),
	"dish_wash": preload("res://audio/mara_dish_wash.mp3"),
	"order_ready": preload("res://audio/mara_order_ready.mp3"),
	"not_yet": preload("res://audio/mara_not_yet.mp3"),
	"here_you_go": preload("res://audio/mara_here_you_go.mp3"),
	"ill_call": preload("res://audio/mara_ill_call.mp3"),
	"chilly": preload("res://audio/mara_chilly.mp3"),
	"dishes_first": preload("res://audio/mara_dishes_first.mp3"),
	"door_ready": preload("res://audio/mara_door_ready.mp3"),
	"lingering": preload("res://audio/mara_lingering.mp3"),
	"practiced_up": preload("res://audio/mara_practiced_up.mp3"),
	"take_time": preload("res://audio/mara_take_time.mp3"),
	"didnt_catch": preload("res://audio/mara_didnt_catch.mp3"),
	"need_card": preload("res://audio/mara_need_card.mp3"),
	"almost_y_con": preload("res://audio/mara_almost_y_con.mp3"),
	"almost_y": preload("res://audio/mara_almost_y.mp3"),
	"almost_con": preload("res://audio/mara_almost_con.mp3"),
	"almost_article": preload("res://audio/mara_almost_article.mp3"),
	"eat_with": preload("res://audio/mara_eat_with.mp3"),
	"drink_with": preload("res://audio/mara_drink_with.mp3"),
	"practice_short": preload("res://audio/mara_practice_short.mp3"),
	"what_call": preload("res://audio/mara_what_call.mp3"),
	"in_spanish": preload("res://audio/mara_in_spanish.mp3"),
	"look_for": preload("res://audio/mara_look_for.mp3"),
	"word_is": preload("res://audio/mara_word_is.mp3"),
	"try_again": preload("res://audio/mara_try_again.mp3"),
	"lovely": preload("res://audio/mara_lovely.mp3"),
	"added_pesos": preload("res://audio/mara_added_pesos.mp3"),
	"pesos_practice": preload("res://audio/mara_pesos_practice.mp3"),
	"practiced_plenty": preload("res://audio/mara_practiced_plenty.mp3"),
	"feel_natural": preload("res://audio/mara_feel_natural.mp3"),
	"that_extra": preload("res://audio/mara_that_extra.mp3"),
	"spanish_wall": preload("res://audio/mara_spanish_wall.mp3"),
	"finish_first": preload("res://audio/mara_finish_first.mp3"),
	"pesos_for": preload("res://audio/mara_pesos_for.mp3"),
	"cant_start": preload("res://audio/mara_cant_start.mp3"),
	"y": preload("res://audio/mara_y.mp3"),
	"con": preload("res://audio/mara_con.mp3"),
	"un": preload("res://audio/mara_un.mp3"),
	"una": preload("res://audio/mara_una.mp3"),
	"cafe": preload("res://audio/mara_cafe.mp3"),
	"te": preload("res://audio/mara_te.mp3"),
	"muffin": preload("res://audio/mara_muffin.mp3"),
	"chocolate": preload("res://audio/mara_chocolate.mp3"),
	"espresso": preload("res://audio/mara_espresso.mp3"),
	"croissant": preload("res://audio/mara_croissant.mp3"),
	"tostada": preload("res://audio/mara_tostada.mp3"),
	"galleta": preload("res://audio/mara_galleta.mp3"),
	"bolillo": preload("res://audio/mara_bolillo.mp3"),
	"leche": preload("res://audio/mara_leche.mp3"),
	"azucar": preload("res://audio/mara_azucar.mp3"),
	"crema": preload("res://audio/mara_crema.mp3"),
	"calentado": preload("res://audio/mara_calentado.mp3"),
	"frio": preload("res://audio/mara_frio.mp3"),
	"coffee": preload("res://audio/mara_coffee.mp3"),
	"tea": preload("res://audio/mara_tea.mp3"),
	"toast": preload("res://audio/mara_toast.mp3"),
	"cookie": preload("res://audio/mara_cookie.mp3"),
	"milk": preload("res://audio/mara_milk.mp3"),
	"sugar": preload("res://audio/mara_sugar.mp3"),
	"creamer": preload("res://audio/mara_creamer.mp3"),
	"hot_chocolate": preload("res://audio/mara_hot_chocolate.mp3"),
}

